package es.ua.dlsi.mejorua.api.util;

import java.io.IOException;

import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;

public class JSON {

	private static ObjectMapper mapper = new ObjectMapper();

	public static String encode(Object o) {
		String json = "";

		// TODO Fill autogenerated catchs or use a generic one
		try {
			json = mapper.writeValueAsString(o);
		} catch (JsonGenerationException e) {
			e.printStackTrace();
		} catch (JsonMappingException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		return json;
	}

	public static Object decode(String JSON, Class<?> c) {

		Object o = null;

		// TODO Fill autogenerated catchs or use a generic one
		try {
			o = mapper.readValue(JSON, c);
		} catch (JsonGenerationException e) {
			e.printStackTrace();
		} catch (JsonMappingException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		return o;
	}
}
