#!/bin/bash

echo "###############################################"
echo "#"
echo "# STARTING - Tomcat - Remote debugging ready"
echo "#"
echo "###############################################"

export JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"

cd $CATALINA_HOME/bin

./catalina.sh jpda start
#./startup.sh

echo "###############################################"
echo "#"
echo "# FINISHED - Tomcat - Remote debugging ready"
echo "#"
echo "###############################################"